# Generated by Django 2.2.5 on 2019-10-12 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idcarrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('grado', models.CharField(max_length=25)),
                ('curso1', models.CharField(max_length=25)),
                ('curso2', models.CharField(max_length=25)),
                ('curso3', models.CharField(max_length=25)),
                ('curso4', models.CharField(max_length=25)),
                ('curso5', models.CharField(max_length=25)),
                ('curso6', models.CharField(max_length=25)),
                ('curso7', models.CharField(max_length=25)),
                ('curso8', models.CharField(max_length=25)),
                ('curso9', models.CharField(max_length=25)),
                ('curso11', models.CharField(max_length=25)),
                ('curso12', models.CharField(max_length=25)),
                ('curso13', models.CharField(max_length=25)),
                ('curso14', models.CharField(max_length=25)),
                ('curso15', models.CharField(max_length=25)),
                ('curso16', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('iddocente', models.IntegerField(primary_key=True, serialize=False)),
                ('pnombre', models.CharField(max_length=25)),
                ('snombre', models.CharField(max_length=25)),
                ('pApellido', models.CharField(max_length=25)),
                ('sApellido', models.CharField(max_length=25)),
                ('fNacimiento', models.DateField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=25)),
                ('idcarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idestudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('pnombre', models.CharField(max_length=25)),
                ('snombre', models.CharField(max_length=25)),
                ('pApellido', models.CharField(max_length=25)),
                ('sApellido', models.CharField(max_length=25)),
                ('fNacimiento', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=25)),
                ('grado', models.CharField(max_length=25)),
                ('codigoCarrera', models.CharField(max_length=25)),
                ('idcarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante_Y_Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Docente')),
                ('idestudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('seccion', models.CharField(max_length=25)),
                ('idcarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Carrera')),
                ('iddocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Docente')),
                ('idestudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Estudiante')),
            ],
        ),
    ]
